### ISSUE TITLE
Add methods to reset PIN and password

### ISSUE THREAD

**Issue by AmrElsayyad** [abhi9720/BankingPortal-API#13]
**Is your feature request related to a problem? Please describe.**
If a user forgets PIN or Password there are no ways to recover.

**Describe the solution you'd like**
Implement methods to reset PIN or password, e.g., via email.

**Comment by AmrElsayyad** [comment]
> I have started development for this, and will update here soon with the PR

Great news! Can you also add confirm PIN for PIN creation?

**Comment by abhi9720** [comment]
> Great news! Can you also add confirm PIN for PIN creation in the UI?
Ok sure, I will do
