### ISSUE TITLE
Add support for Lombok dependency

### ISSUE THREAD

**Issue by iammohsinar** [abhi9720/BankingPortal-API#24]
I can see a lot setter and getter methods and autowired annotations on service layer. To look more clear and readable we can add lombok support in backend system.

**Comment by AmrElsayyad** [comment]
Good idea. I will work on this.

**Comment by abhi9720** [comment]
What If we use both Record and Lombok?
**Records**: for simple, immutable data structures like DTOs used in API responses.
**Lombok**: for more complex and mutable classes, such as entities and DTOs that need additional behaviour or configuration.

**Comment by AmrElsayyad** [comment]
@abhi9720 
Yes, I was thinking that, too.
