### ISSUE TITLE
Swagger UI for Documentation is comprehensible for both developers and non-developers like clients or project managers.

### ISSUE THREAD

**Issue by Kordedekehine** [abhi9720/BankingPortal-API#3]
**Is your feature request related to a problem? Please describe.**
For developers and non developers that might take interest in this project might need swagger UI for easy documentation and comprehension

**Describe the solution you'd like**
Implement swagger UI. I mean the Open API version

**Describe alternatives you've considered**
Postman is an alternative sure. But it does not make documentation as easy and comprehensible as swagger UI

**Additional context**
I want to ask if I can go ahead with implementing swagger with the app

**Comment by abhi9720** [comment]
Hi @Kordedekehine,

Thank you for your suggestion. I want to let you know that I have added the Swagger API as well.

**Comment by abhi9720** [comment]
Hi @Kordedekehine,

Thank you for your suggestion. I want to let you know that I have added the Swagger API as well.

**Comment by Kordedekehine** [comment]
You are welcome. If there is anyway I can contribute kindly let me know please

**Comment by abhi9720** [comment]
> You are welcome. If there is anyway I can contribute kindly let me know please

checkout readme file: https://github.com/abhi9720/BankingPortal-API?tab=readme-ov-file#how-to-contribute
